/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	medalv1 "hccl-controller/pkg/apis/training/medal/v1"
	versioned "hccl-controller/pkg/client/training/medal/clientset/versioned"
	internalinterfaces "hccl-controller/pkg/client/training/medal/informers/externalversions/internalinterfaces"
	v1 "hccl-controller/pkg/client/training/medal/listers/medal/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MedalJobInformer provides access to a shared informer and lister for
// MedalJobs.
type MedalJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MedalJobLister
}

type medalJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMedalJobInformer constructs a new informer for MedalJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMedalJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMedalJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMedalJobInformer constructs a new informer for MedalJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMedalJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MeituanV1().MedalJobs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MeituanV1().MedalJobs(namespace).Watch(context.TODO(), options)
			},
		},
		&medalv1.MedalJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *medalJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMedalJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *medalJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&medalv1.MedalJob{}, f.defaultInformer)
}

func (f *medalJobInformer) Lister() v1.MedalJobLister {
	return v1.NewMedalJobLister(f.Informer().GetIndexer())
}
