- name: include vars
  include_vars: ../defaults/main.yml

- name: create group {{ DL_GRP }}
  ansible.builtin.group:
    name: "{{ DL_GRP }}"
    state: present
    gid: "{{ DL_GID }}"
  ignore_errors: true

- name: create group {{ HIAI_GROUP }}
  ansible.builtin.group:
    name: "{{ HIAI_GROUP }}"
    state: present
  ignore_errors: true

- name: create user {{ DL_USR }}
  ansible.builtin.user:
    name: "{{ DL_USR }}"
    comment: "{{  DL_USR }}"
    uid: "{{ DL_UID }}"
    group: "{{ DL_GRP }}"
    groups: "{{ MINDX_GROUP }}"
    append: yes
    state: present
    shell: /usr/sbin/nologin
  ignore_errors: true

- name: create log directories
  file:
    path: /var/log/mindx-dl
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install haveged for ubuntu
  shell: dpkg --force-all -i {{ haveged_dir }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - OS_ID == 'ubuntu'
    - OS_VERSION_ID == '18.04'

- name: install haveged for centos
  shell: rpm -ivh --force --nodeps --replacepkgs {{ haveged_dir }}/*.rpm
  when:
    - OS_ID == 'centos'
    - OS_VERSION_ID == '7'
