- name: include vars
  include_vars: ../defaults/main.yml

- name: create log directories
  file:
    path: /var/log/mindx-dl
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install haveged for ubuntu
  shell: dpkg --force-all -i {{ haveged_dir }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when: OS_ID == 'ubuntu'

- name: install haveged for not ubuntu
  shell: rpm -ivh --force --nodeps --replacepkgs {{ haveged_dir }}/*.rpm
  when: OS_ID != 'ubuntu'

- name: enable haveged
  systemd:
    name: "haveged"
    enabled: true
    state: started
