- include_tasks: master_basic.yml
  when: ansible_connection == "local"

- name: delete old hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regex: "127.0.*{{ansible_hostname}}"
    state: absent

- name: set hostname
  ansible.builtin.hostname:
    name: "{{set_hostname}}"
  when: set_hostname is defined

- name: add new hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.1.1 {{ set_hostname }}"
  when: set_hostname is defined
