- name: create yaml directory
  file:
    path: "{{ PROM_YAML_DIR }}"
    state: directory
    mode: 0750

- name: create prometheus node-exporter grafana yamls
  template:
    src: "{{ item }}"
    dest: "{{ PROM_YAML_DIR }}/{{ item }}"
    mode: 0640
  with_items:
    - prometheus.yaml
    - node-exporter.yaml
    - grafana.yaml

- name: deploy yamls
  shell: kubectl apply -f {{ PROM_YAML_DIR }}/{{ item }}
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  with_items:
    - prometheus.yaml
    - node-exporter.yaml
    - grafana.yaml
