- name: message
  debug:
    msg: "******************************start install nfs server******************************"

- name: install nfs server for ubuntu
  shell: |
      dpkg --force-all -i {{ client_pkg }}/*.deb
      dpkg --force-all -i {{ server_pkg }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - OS_ID == 'ubuntu'
    - OS_VERSION_ID == '18.04'

- name: install nfs server for centos
  shell: |
      rpm -ivh --force --nodeps --replacepkgs {{ client_pkg }}/*.rpm
      rpm -ivh --force --nodeps --replacepkgs {{ server_pkg }}/*.rpm
  when:
    - OS_ID == 'centos'
    - OS_VERSION_ID == '7'

- name: create nfs path
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ DL_USR }}"
    group: "{{ DL_GRP }}"
    mode: 0750
  loop:
    - "{{ DL_PATH }}"
    - "{{ PLATFORM_PATH }}"
    - "{{ PLATFORM_PATH }}/kmc"
    - "{{ PLATFORM_PATH }}/log"
    - "{{ PLATFORM_PATH }}/log/apigw"
    - "{{ PLATFORM_PATH }}/log/apigw-business"
    - "{{ PLATFORM_PATH }}/log/cluster-manager"
    - "{{ PLATFORM_PATH }}/log/data-manager"
    - "{{ PLATFORM_PATH }}/log/dataset-manager"
    - "{{ PLATFORM_PATH }}/log/model-manager"
    - "{{ PLATFORM_PATH }}/log/inference-manager"
    - "{{ PLATFORM_PATH }}/log/train-manager"
    - "{{ PLATFORM_PATH }}/log/user-manager"
    - "{{ PLATFORM_PATH }}/log/alarm-manager"
    - "{{ PLATFORM_PATH }}/services"
    - "{{ PLATFORM_PATH }}/services/prometheus"

- name: create nfs path for image-manager log
  file:
    path: "{{ PLATFORM_PATH }}/log/image-manager"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: copy rule.yaml
  copy:
    src: "{{role_path}}/files/rule.yaml"
    dest: "{{ PLATFORM_PATH }}/services/prometheus/rule.yaml"
    owner: "{{ DL_USR }}"
    group: "{{ DL_GRP }}"
    mode: 0600

- name: config nfs /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: "^{{ item.path }} "
    line: "{{ item.path }} {{ MASTER_WORKER_IP | join('(rw,sync,no_root_squash) ') | replace('localhost', MASTER_IP) }}(rw,sync,no_root_squash)"
    state: present
  loop:
    - { "path": "{{ DL_PATH }}" }

- name: "restart nfs"
  systemd:
    name: "nfs-server"
    enabled: true
    state: restarted
