---
# distribute resources
- hosts:
    - master
    - worker
    - harbor
    - master_backup
  roles:
    - role: mindx.resource
      vars:
        resource_list:
          - linux_aarch64
          - linux_x86_64
          - ubuntu_18.04_aarch64
          - ubuntu_18.04_x86_64
          - centos_7_aarch64

# copy nfs resources to nfs_server host
- hosts:
    - nfs_server
  roles:
    - role: mindx.resource
      when: STORAGE_TYPE == "NFS"
      vars:
        resource_list:
          - ubuntu_18.04_aarch64
          - ubuntu_18.04_x86_64
          - centos_7_aarch64

# copy harbor install package to harbor host
- hosts: harbor
  gather_facts: False
  roles:
    - role: mindx.resource
      vars:
        resource_list:
          - harbor-offline-installer-v2.3.3.tgz
          - harbor-offline-installer-aarch64-v2.3.3.tgz

# install softwares
- hosts:
    - master
    - worker
    - master_backup
  gather_facts: False
  roles:
    - role: mindx.docker
    - role: mindx.k8s.install
    - role: mindx.nfs.client
      when: STORAGE_TYPE == "NFS"

# install harbor
- hosts:
    - harbor
  gather_facts: False
  roles:
    - role: mindx.docker
    - role: mindx.harbor.install

- hosts:
    - master
    - worker
    - master_backup
  gather_facts: False
  roles:
    - role: mindx.harbor.login

- hosts: master
  gather_facts: False
  roles:
    - role: mindx.harbor.push
      vars:
        project_list:
          - k8s.gcr.io
          - dockerhub
          - prom
          - grafana
          - mysql
          - openresty
          - calico
          - ghcr.io
        project_public: "true"
        images_dir: images

# set basic config for mindxdl
- hosts:
    - master
    - worker
    - master_backup
  gather_facts: False
  tasks:
  - include_tasks: playbooks/roles/mindx.basic/tasks/common.yml

- hosts:
    - master
    - master_backup
  gather_facts: False
  tasks:
  - include_tasks: playbooks/roles/mindx.basic/tasks/master.yml

- hosts: worker
  gather_facts: False
  tasks:
  - include_tasks: playbooks/roles/mindx.basic/tasks/worker.yml

# master init k8s
- hosts: master
  gather_facts: False
  roles:
    - role: mindx.k8s.kubevip
    - role: mindx.k8s.master

# master_backup join k8s
- hosts: master_backup
  gather_facts: False
  roles:
    - role: mindx.k8s.master_backup
    - role: mindx.k8s.kubevip

# worker join k8s
- hosts: worker
  gather_facts: False
  roles:
    - role: mindx.k8s.worker
    - role: mindx.k8s.autolabel

# install nfs server
- hosts: nfs_server
  gather_facts: False
  roles:
    - role: mindx.nfs.server
      when: STORAGE_TYPE == "NFS"

# create pv and pvc
- hosts: master
  gather_facts: False
  roles:
    - role: mindx.k8s.nfspv
      when: STORAGE_TYPE == "NFS"
      vars:
        pv_name: storage-pv-mindx-dl
        capacity: "{{ DL_CAP }}"
        path: "{{ DL_PATH }}"
        claimRef_name: storage-pvc
    - role: mindx.k8s.cephfspv
      when: STORAGE_TYPE == "CEPHFS"
      vars:
        pv_name: storage-pv-mindx-dl
        capacity: "{{ DL_CAP }}"
        path: "{{ DL_PATH }}"
        claimRef_name: storage-pvc
    - role: mindx.k8s.pvc
      vars:
        pvc_name: storage-pvc
        capacity: "{{ DL_CAP }}"

# mysql、redis、prom
- hosts: master
  gather_facts: False
  roles:
    - role: mindx.mysql
    - role: mindx.redis
    - role: mindx.k8s.prom

# push inner-images to harbor
- hosts: master
  gather_facts: False
  roles:
    - role: mindx.harbor.push
      vars:
        project_list:
          - mindx
        project_public: "false"
        images_dir: mindx-inner-images

# push pre-images to harbor
- hosts: master
  gather_facts: False
  roles:
    - role: mindx.harbor.push
      vars:
        project_list:
          - mindx
        project_public: "false"
        images_dir: mindx-pre-images
