apiVersion: v1
kind: ConfigMap
metadata:
  name: rings-config-{{ job_name }}      # The prefix "rings-config-" cannot be modified
  labels:
    ring-controller.atlas: ascend-910    # Not modifiable
data:
  hccl.json: |
    {
        "status":"initializing"
    }