# Copyright © Huawei Technologies Co., Ltd. 2020. All rights reserved.
---
# Generate report with master

- hosts: master
  remote_user: root

  tasks:
    - name: Set reports dir facts
      add_host:
        name: "master_reports"
        report_dir: "{{ playbook_dir }}/MindXReport"

    - name: Create result dir
      file:
        path: "{{ hostvars['master_reports']['report_dir'] }}"
        state: directory
        mode: 0700

    - name: Change file mode
      file:
        path: "{{ playbook_dir }}/collect_log.py"
        mode: 0500
      ignore_errors: True

    - name: collect log - master nodes
      shell:
        chdir: "{{ playbook_dir }}"
        cmd:
          dos2unix collect_log.py;
          python collect_log.py >> /dev/null 2>&1
      when:
        - ansible_hostname in groups["master"]

    - name: mv report on master
      shell:
        chdir: "{{ playbook_dir }}"
        cmd:
          mv MindX_Report*.gz {{ hostvars['master_reports']['report_dir'] }}/
      when:
        - ansible_hostname in groups["master"]


# Generate report with worker
- hosts: workers
  remote_user: root
  vars:
    tmp_dir: "/tmp/MindXReport/"

  tasks:
    - name: Remove old file on workers
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tmp_dir }}/collect_log.py"
        - "{{ tmp_dir }}"
      ignore_errors: True
      when:
        - ansible_hostname not in groups["master"]

    - name: create remote dir  - worker nodes
      file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: 0700
      when:
        - ansible_hostname not in groups["master"]

    - name: Copy collect_log.py to workers
      copy:
        src: "{{ playbook_dir }}/collect_log.py"
        dest: "{{ tmp_dir }}/collect_log.py"
        mode: 0500
      when:
        - ansible_hostname not in groups["master"]

    - name: collect log  - worker nodes
      shell:
        chdir: "{{ tmp_dir }}"
        cmd:
          python collect_log.py master >> /dev/null 2>&1
      when:
        - ansible_hostname not in groups["master"]

    # copy from worker node
    - name: find report file from workers
      find:
        paths: "{{ tmp_dir }}"
        patterns: "MindX_Report*.gz"
        recurse: True
      register: file_name
      when:
        - ansible_hostname not in groups["master"]

    - name: Get report from workers
      fetch:
        src: "{{ item.path }}"
        dest: "{{ hostvars['master_reports']['report_dir'] }}/"
        flat: True
      with_items: " {{ file_name.files }} "
      when:
        - ansible_hostname not in groups["master"]

    - name: Remove temporary file on workers
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tmp_dir }}/collect_log.py"
        - "{{ tmp_dir }}"
      ignore_errors: True
      when:
        - ansible_hostname not in groups["master"]


# deal collect log in master
- hosts: master
  remote_user: root

  tasks:
    - name: mv and Change file right
      shell:
        chdir: "{{ playbook_dir }}"
        cmd:
          mv MindX_Report*.gz {{ hostvars['master_reports']['report_dir'] }}/ || true;
          chmod -R 400 {{ hostvars['master_reports']['report_dir'] }}/MindX_Report*.gz || true;
          chown -R root:root {{ hostvars['master_reports']['report_dir'] }}
      ignore_errors: True
      when:
        - ansible_hostname in groups["master"]

    - name: Print report path
      shell:
        cmd:
          echo "Finished! The check report is stored in {{ playbook_dir }}/MindXReport/ on the master node."
