apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: {{ capacity }}
  hostPath:
    path: {{ data_path }}
