- name: install docker-ce
  shell: dpkg --force-all -i {{resource_dir}}/{{OS_ID}}_{{OS_VERSION_ID}}_{{ansible_architecture}}/docker/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - OS_ID == 'ubuntu'
    - OS_VERSION_ID == '18.04'

- name: "restart docker"
  systemd:
    name: "docker"
    enabled: true
    state: restarted
