apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pv-claim
  namespace: {{ K8S_NAMESPACE }}
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ CEPHFS_REQUEST_STORAGE }}
