apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv
spec:
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: {{ CEPHFS_REQUEST_STORAGE }}
  cephfs:
    monitors:
      - {{ CEPHFS_IP }}:{{ CEPHFS_PORT }}
    user: {{ CEPHFS_USER }}
    secretRef:
      name: ceph-secret
      namespace: {{ K8S_NAMESPACE }}
  claimRef:
    name: cephfs-pv-claim
    namespace: {{ K8S_NAMESPACE }}
  persistentVolumeReclaimPolicy: Retain
