---
- hosts: localnode
  remote_user: root

  vars:
    yaml_dir: "{{playbook_dir}}/../yamls/"

  tasks:
    - name: Remove /var/log/atlas_dls
      shell:
        cmd: rm -rf /var/log/atlas_dls
      ignore_errors: True

    - name: Create dls_core log directory
      file:
        path: /var/log/atlas_dls/{{ item }}
        state: directory
        mode: "0750"
        owner: 'hwMindX'
        group: 'hwMindX'
      with_items:
        - volcano-controller
        - volcano-scheduler
        - volcano-admission
        - hccl-controller

    - name: Create log directory for cadvisor and device-plugin
      file:
        path: /var/log/{{ item }}
        state: directory
        mode: "0750"
      with_items:
        - devicePlugin
        - cadvisor

    - name: Add scheduler log config information
      blockinfile:
        path: /etc/logrotate.d/mindx_dl_scheduler
        block: |
          /var/log/atlas_dls/volcano-*/*.log
          /var/log/atlas_dls/hccl-*/*.log{
              daily
              rotate 8
              size 20M
              compress
              dateext
              missingok
              notifempty
              copytruncate
              create 0640 hwMindX hwMindX
              sharedscripts
              postrotate
                  chmod 640 /var/log/atlas_dls/volcano-*/*.log
                  chmod 640 /var/log/atlas_dls/hccl-*/*.log
                  chmod 440 /var/log/atlas_dls/volcano-*/*.log-*
                  chmod 440 /var/log/atlas_dls/hccl-*/*.log-*
              endscript
          }
        state: present
        create: yes

    - name: Add acvisor log config information
      blockinfile:
        path: /etc/logrotate.d/mindx_dl_advisor
        block: |
          /var/log/devicePlugin/*.log
          /var/log/cadvisor/*.log{
              daily
              rotate 8
              size 20M
              compress
              dateext
              missingok
              notifempty
              copytruncate
              create 0640 root root
              sharedscripts
              postrotate
                  chmod 640 /var/log/devicePlugin/*.log
                  chmod 640 /var/log/cadvisor/*.log
                  chmod 440 /var/log/devicePlugin/*.log-*
                  chmod 440 /var/log/cadvisor/*.log-*
              endscript
          }
        state: present
        create: yes

    - name: Deploy hccl-controller
      shell:
        chdir: "{{yaml_dir}}"
        cmd:
          kubectl apply -f hccl-controller*.yaml

    - name: Deploy device plugin
      shell:
        chdir: "{{yaml_dir}}"
        cmd:
          kubectl apply -f ascendplugin-volcano*.yaml;
          kubectl apply -f ascendplugin-310*.yaml

    - name: Deploy cadvisor
      shell:
        chdir: "{{yaml_dir}}/kubernetes/overlays"
        cmd:
          kubectl apply -k huawei

    - name: Deploy volcano
      shell:
        chdir: "{{yaml_dir}}"
        cmd:
          kubectl apply -f volcano-*.yaml
