- name: message
  debug:
    msg: "*************************start install ceph***************************"

- name: set hostname
  ansible.builtin.hostname:
    name: "{{set_hostname}}"
  when: set_hostname is defined

- name: install cephadm
  copy:
    src: "{{resource_dir}}/cephadm/cephadm"
    dest: /usr/sbin/cephadm
    mode: "0750"
  when: ansible_connection == "local"

- name: install ceph-common
  shell: dpkg --force-all -i {{resource_dir}}/{{OS_ID}}_{{OS_VERSION_ID}}_{{ansible_architecture}}/ceph-common/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - OS_ID == 'ubuntu'
    - OS_VERSION_ID == '18.04'
