/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "hccl-controller/pkg/apis/training/medal/v1"
	scheme "hccl-controller/pkg/client/training/medal/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MedalJobsGetter has a method to return a MedalJobInterface.
// A group's client should implement this interface.
type MedalJobsGetter interface {
	MedalJobs(namespace string) MedalJobInterface
}

// MedalJobInterface has methods to work with MedalJob resources.
type MedalJobInterface interface {
	Create(ctx context.Context, medalJob *v1.MedalJob, opts metav1.CreateOptions) (*v1.MedalJob, error)
	Update(ctx context.Context, medalJob *v1.MedalJob, opts metav1.UpdateOptions) (*v1.MedalJob, error)
	UpdateStatus(ctx context.Context, medalJob *v1.MedalJob, opts metav1.UpdateOptions) (*v1.MedalJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.MedalJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.MedalJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MedalJob, err error)
	MedalJobExpansion
}

// medalJobs implements MedalJobInterface
type medalJobs struct {
	client rest.Interface
	ns     string
}

// newMedalJobs returns a MedalJobs
func newMedalJobs(c *MeituanV1Client, namespace string) *medalJobs {
	return &medalJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the medalJob, and returns the corresponding medalJob object, and an error if there is any.
func (c *medalJobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.MedalJob, err error) {
	result = &v1.MedalJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("medaljobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MedalJobs that match those selectors.
func (c *medalJobs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.MedalJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MedalJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("medaljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested medalJobs.
func (c *medalJobs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("medaljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a medalJob and creates it.  Returns the server's representation of the medalJob, and an error, if there is any.
func (c *medalJobs) Create(ctx context.Context, medalJob *v1.MedalJob, opts metav1.CreateOptions) (result *v1.MedalJob, err error) {
	result = &v1.MedalJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("medaljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(medalJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a medalJob and updates it. Returns the server's representation of the medalJob, and an error, if there is any.
func (c *medalJobs) Update(ctx context.Context, medalJob *v1.MedalJob, opts metav1.UpdateOptions) (result *v1.MedalJob, err error) {
	result = &v1.MedalJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("medaljobs").
		Name(medalJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(medalJob).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *medalJobs) UpdateStatus(ctx context.Context, medalJob *v1.MedalJob, opts metav1.UpdateOptions) (result *v1.MedalJob, err error) {
	result = &v1.MedalJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("medaljobs").
		Name(medalJob.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(medalJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the medalJob and deletes it. Returns an error if one occurs.
func (c *medalJobs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("medaljobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *medalJobs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("medaljobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched medalJob.
func (c *medalJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.MedalJob, err error) {
	result = &v1.MedalJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("medaljobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
