- name: message
  debug:
    msg: "******************************start deploy mysql******************************"

- name: message
  debug:
    msg: "no mysql password is set, please check"
  failed_when: true
  when: MYSQL_PASSWORD | length == 0

- name: create deploy directory on host
  file:
    path: "{{ MYSQL_YAML_DIR }}"
    state: directory
    mode: 0750

- name: create Dockerfile
  template:
    src: "{{ item }}"
    dest: "{{ MYSQL_YAML_DIR }}/{{ item }}"
    mode: 0640
  with_items:
    - init.sql
    - Dockerfile
    - my.cnf

- name: build and push mysql docker image
  shell: |
    # docker build {{ MYSQL_YAML_DIR }} -t mysql-dl:8.0.26
    docker build {{ MYSQL_YAML_DIR }} -t {{REPO_URL}}mysql/mysql-dl_{{ARCH}}:8.0.26
    docker push {{REPO_URL}}mysql/mysql-dl_{{ARCH}}:8.0.26
    docker manifest create {{REPO_URL}}mysql/mysql-dl:8.0.26 \
    {{REPO_URL}}mysql/mysql-dl_{{ARCH}}:8.0.26 -a
    docker manifest annotate {{REPO_URL}}mysql/mysql-dl:8.0.26 \
    {{REPO_URL}}mysql/mysql-dl_{{ARCH}}:8.0.26 --os linux --arch {{ARCH}}
    docker manifest push {{REPO_URL}}mysql/mysql-dl:8.0.26
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    DOCKER_CLI_EXPERIMENTAL: enabled

- name: check namespace
  shell: "kubectl get namespace | awk '$1 ~ /^{{ k8s_namespace }}$/ {print $1}'"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  changed_when: false
  register: get_namespace

- name: create namespace
  shell: "kubectl create namespace {{ k8s_namespace }}"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  when: get_namespace.stdout != k8s_namespace

- name: create secret for mysql
  shell: |
    kubectl delete secret --namespace={{ k8s_namespace }} dbsecret --ignore-not-found=true
    kubectl create secret --namespace={{ k8s_namespace }} generic dbsecret --from-literal="root_pwd={{pwd}}"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""

- name: create secret for service
  shell: |
    kubectl delete secret --namespace={{ k8s_namespace }} mysql-secret-{{item.service}}
    kubectl create secret \
    --namespace={{ k8s_namespace }} \
    generic mysql-secret-{{item.service}} \
    --from-literal='connection-path={{item.user}}:{{pwd}}@tcp(mysql.{{ k8s_namespace }}.svc.cluster.local:3306)/{{item.dbname}}?charset=utf8&parseTime=True&loc=Local'
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  with_items:
    - { "user":"user_user",    "dbname":"dl_platform",    "service": "user-manager"}
    - { "user":"dataset_user", "dbname":"dl_platform", "service": "dataset-manager"}
    - { "user":"train_user",   "dbname":"dl_platform",   "service": "train-manager"}
    - { "user":"model_user",   "dbname":"dl_platform",   "service": "model-manager"}
    - { "user":"inference_user",    "dbname":"dl_platform",    "service": "inference-manager"}
    - { "user":"image_user",   "dbname":"dl_platform",   "service": "image-manager"}
    - { "user":"data_user",    "dbname":"dl_platform",    "service": "data-manager"}
    - { "user":"cluster_user", "dbname":"dl_platform", "service": "cluster-manager"}
    - { "user":"alarm_user",   "dbname":"dl_platform",   "service": "alarm-manager"}

- name: create yamls
  template:
    src: "{{ item }}"
    dest: "{{ MYSQL_YAML_DIR }}/{{ item }}"
    mode: 0640
  with_items:
    - mysql-deployment.yaml

- name: deploy mysql
  shell: "kubectl apply -f {{ MYSQL_YAML_DIR }}/{{ item }}"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  with_items:
    - mysql-deployment.yaml
