- name: message
  debug:
    msg: "**********start install MindX DL********************"

- name: message
  debug:
    msg: "APIGW_LOADBALANCER_IP can not be empty in group_vars/all.yaml, please check"
  failed_when: true
  when: APIGW_LOADBALANCER_IP | length == 0

- name: create image-pull-secret
  shell: |
    kubectl delete secret --namespace={{ K8S_NAMESPACE }} image-pull-secret
    kubectl create secret docker-registry image-pull-secret \
    --namespace={{ K8S_NAMESPACE }} \
    --docker-server={{ HARBOR_IP }}:{{ HARBOR_HTTPS_PORT }} --docker-username=admin --docker-password={{ HARBOR_PASSWORD }}
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""

- name: copy dlinstall script
  copy:
    src: "{{role_path}}/files/dlinstall"
    dest: /usr/bin/
    mode: 0700

- name: install MindX DL
  shell: "/usr/bin/dlinstall --harbor-ip {{ HARBOR_IP }} --harbor-port {{ HARBOR_HTTPS_PORT }} {{ item }}"
  ignore_errors: true
  when: "ansible_architecture in item"
  with_fileglob:
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-cluster-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-apigw*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-user-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-data-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-dataset-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-image-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-model-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-inference-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-train-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-alarm-manager*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-hccl-controller*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-volcano*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-npu-exporter*.zip"
    - "{{ resource_dir }}/mindxdl/Ascend-mindxdl-device-plugin*.zip"

- name: create deploy directory on host
  file:
    path: "{{ APIGW_YAML_DIR }}"
    state: directory
    mode: 0750

- name: create yamls
  template:
    src: "{{ item }}"
    dest: "{{ APIGW_YAML_DIR }}/{{ item }}"
    mode: 0640
  with_items:
    - apigw-loadbalancer.yaml
    - apigw-business-loadbalancer.yaml

- name: expose loadbalancer
  shell: "kubectl apply -f {{ APIGW_YAML_DIR }}/{{ item }}"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  with_items:
    - apigw-loadbalancer.yaml
    - apigw-business-loadbalancer.yaml

- name: message
  debug:
    msg:
      - "Mindx DL Platform is now available at: https://{{ APIGW_LOADBALANCER_IP }}:{{ APIGW_LOADBALANCER_PORT }}"
