- name: install docker-ce for ubuntu
  shell: dpkg --force-all -i {{ pkg_dir }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - OS_ID == 'ubuntu'
    - OS_VERSION_ID == '18.04'

- name: install docker-ce for centos or openEuler
  shell: rpm -ivh --force --nodeps --replacepkgs {{ pkg_dir }}/*.rpm
  when: OS_ID != 'ubuntu'

- name: restart docker
  shell: systemctl restart docker
  when: OS_ID != 'ubuntu'

- name: config docker
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
    mode: 0600

- name: restart docker
  systemd:
    name: "docker"
    enabled: true
    state: restarted
