- name: docker load -i {{image}}
  shell: "docker load -i {{ image }}"
  register: load_result

- name: analyze image
  set_fact:
    manifest_name: '{{ (line.split(":")[1] | trim).split("_")[:-1] | join("_") }}'
    arch: '{{ ((line.split(":")[1] | trim).split("_")[-1]) }}'
    orig_name: '{{line.split(":")[1:] | join(":") | trim }}'
    tag: '{{ line.split(":")[-1] | trim }}'
  with_items: "{{ load_result.stdout_lines }}"
  when: '"Loaded image" in line'
  loop_control:
    loop_var: line

- name: create manifest and push {{orig_name}} to harbor
  shell: |
    docker tag {{orig_name}} {{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{orig_name}}
    docker push {{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{orig_name}}
    docker manifest create {{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{manifest_name}}:{{tag}} {{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{orig_name}} -a
    docker manifest annotate {{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{manifest_name}}:{{tag}} {{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{orig_name}} --os linux --arch {{arch}}
    docker manifest push {{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{manifest_name}}:{{tag}}
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    DOCKER_CLI_EXPERIMENTAL: enabled

- name: query mysql pod
  shell: "kubectl get pod -n {{ k8s_namespace }} -l app=mysql | awk 'END {print $1}'"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  register: mysql_pod
  when: "'mindx' in images_dir"

- name: query image size
  shell: docker image ls | awk '$1 ~ /^{{ manifest_name | replace("/", "\/") }}_{{arch}}$/ && $2 ~ /^{{tag}}$/ {print $NF}'
  register: image_size
  when: "'mindx' in images_dir"

- name: insert image info to mysql
  shell: |
    kubectl exec {{ mysql_pod.stdout }} -n {{ k8s_namespace }} -- \
    mysql -u image_user -p{{ MYSQL_PASSWORD }} -e \
    "USE dl_platform; \
    INSERT IGNORE INTO image_configs(image_name, image_tag, image_size, harbor_path, prefabricated, image_arch, create_time, image_usage) \
    VALUES('{{manifest_name.split('/')[-1]}}', '{{tag}}', \
    {{ (image_size.stdout | replace(image_size.stdout[-2:], '') | float) * ((1024 if 'GB' in image_size.stdout else 1) | float) }}, \
    '{{HARBOR_IP}}:{{HARBOR_HTTPS_PORT}}/{{harbor_path}}:{{tag}}', {{prefabricated}}, '{{image_arch}}', NOW(), '{{image_usage}}');"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  when: "'mindx' in images_dir"
