- name: message
  debug:
    msg: "******************************start create kubevip on master******************************"

- name: check KUBE_VIP and KUBE_INTERFACE
  debug:
    msg: "KUBE_VIP and KUBE_INTERFACE can not be empty in group_vars/all.yaml, please check"
  failed_when: true
  when: KUBE_VIP | length == 0 or KUBE_INTERFACE | length == 0

- name: message
  debug:
    msg: "master_backup is suggested to contain 2 nodes at least in inventory_file, please check"
  failed_when: true
  when:
    - "'master_backup' in groups"
    - "groups['master_backup'] | length == 1"

- name: check k8s
  shell: "kubectl cluster-info | grep 'is running at' | wc -l"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  register: cluster_info

- name: message
  debug:
    msg: "k8s is running already, please check"
  failed_when: true
  when: cluster_info.stdout != "0"

- name: create /etc/kubernetes/manifests/
  file:
    path: /etc/kubernetes/manifests/
    state: directory
    mode: 0700
  ignore_errors: true

- name: generate kube-vip.yaml
  shell: |
    docker run --network host --rm {{ REPO_URL }}{{ KUBE_VIP_IMAGE }}:{{ KVVERSION }} manifest pod \
    --interface {{ KUBE_INTERFACE }} \
    --address {{ KUBE_VIP }} \
    --controlplane \
    --services \
    --arp \
    --leaderElection | tee /etc/kubernetes/manifests/kube-vip.yaml
