- name: message
  debug:
    msg: "******************************start install nfs client******************************"

- name: set MASTER_WORKER_IP
  set_fact:
    MASTER_WORKER_IP: "{{ play_hosts }}"
    cacheable: yes

- name: install nfs client for ubuntu
  shell: dpkg --force-all -i {{ client_pkg }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - OS_ID == 'ubuntu'
    - OS_VERSION_ID == '18.04'

- name: install nfs client for centos or openEuler
  shell: rpm -ivh --force --nodeps --replacepkgs {{ client_pkg }}/*.rpm
  when: OS_ID != 'ubuntu'
