---
# This playbook is used to initialize the K8S cluster.
# Before running this script, ensure that Docker has been installed and the basic image of K8S has been imported.

- hosts: cluster
  remote_user: root

  tasks:
    - name: unset proxy
      shell:
        cmd:
          unset http_proxy https_proxy
      tags: common

# init master
- hosts: master
  remote_user: root
  vars:
    deploy_yaml_dir: "{{dls_root_dir}}/yaml"

  tasks:
    - name: reset k8s
      shell:
        cmd:
          kubeadm reset -f;
          rm -rf /etc/cni/net.d /root/.kube/
      tags: init-master

    - name: Init cluster
      shell:
        cmd:
          kubeadm init --kubernetes-version=v1.17.3
            --node-name={{ansible_hostname}}
            --pod-network-cidr=192.168.0.0/16
            --apiserver-advertise-address={{ master_ip }}
      tags: init-master

    - name: Set kubernetes config file
      shell:
        cmd:
          mkdir -p $HOME/.kube;
          cp -i /etc/kubernetes/admin.conf $HOME/.kube/config;
          chown $(id -u):$(id -g) $HOME/.kube/config;
      tags: init-master

    # apply deploy/yaml/calico.yaml
    - name: Apply calico yaml file
      shell:
        chdir: "{{deploy_yaml_dir}}"
        cmd:
          kubectl apply -f calico.yaml
      tags: init-master

    # use command: kubectl get pods -n kube-system
    # it's successful for releasing node if pod status is "Running"
    - name: Release master node quarantine
      shell:
        cmd:
          kubectl taint nodes --all node-role.kubernetes.io/master-
      tags: init-master

    # add kubeconfig file.  Replaces it if exists or add it if not exists.
    - name: Add kubeconfig file
      lineinfile:
        path: /etc/profile
        regexp: 'export KUBECONFIG(.*)=(.*)/etc'
        line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
      tags: init-master

    # find no_proxy var
    - name: register var
      shell: grep "export no_proxy" /etc/profile
      ignore_errors: True
      register: has_no_proxy_var
      tags: init-master

    # add when no_proxy exists
    - name: Set no proxy ip
      replace:
        path: /etc/profile
        regexp: '(export no_proxy)(.*)'
        replace: '\1\2,{{ master_ip }}'
      when: has_no_proxy_var.stdout != ""
      tags: init-master

    # create no_proxy when no_proxy exists
    - name: Add no proxy ip
      lineinfile:
        path: /etc/profile
        line: 'export no_proxy={{ master_ip }}'
      when: has_no_proxy_var.stdout == ""
      tags: init-master

    - name: Enable /etc/profile
      shell:
        cmd:
          source /etc/profile
      args:
        executable: "/bin/bash"
      tags: init-master

    - name: Label master node
      shell:
        cmd:
          kubectl label nodes {{ansible_hostname}} masterselector=dls-master-node
      tags: init-master


# print join cluster command
- hosts: master
  remote_user: root

  tasks:
    - name: Register join commomd
      shell:
        cmd:
          kubeadm token create --print-join-command
      register: join_command
      tags: init-workers

    - name: Print join cluster command
      debug: var=join_command.stdout
      tags: init-workers


# init workers
- hosts: workers
  remote_user: root
  vars_prompt:
    - name: "join_cluster_command"
      prompt: "Input the command of joining into cluster"
      default: ""
      private: no

  tasks:
    - name: reset k8s
      shell:
        cmd:
          kubeadm reset -f;
          rm -rf /etc/cni/net.d /root/.kube/
      tags: init-master
      ignore_errors: True

    - name: Join into cluster
      shell:
        cmd: "{{join_cluster_command}}"
      tags: init-workers

    # copy local admin.conf to workers
    - name: copy local kubelet.conf to workers
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /etc/kubernetes/
        backup: yes
      tags: init-workers

    - name: Add worker kubeconfig file
      lineinfile:
        path: /etc/profile
        regexp: 'export KUBECONFIG(.*)=(.*)/etc'
        line: 'export KUBECONFIG=/etc/kubernetes/kubelet.conf'
      tags: init-workers

    - name: Enable /etc/profile
      shell:
        cmd:
          source /etc/profile
          systemctl daemon-reload;
          systemctl restart kubelet;
      args:
        executable: "/bin/bash"
      tags: init-workers

# Label worker node
- hosts: master
  remote_user: root

  tasks:
    - name: Label training nodes - arm64
      shell:
        cmd:
          kubectl label nodes {{item}} node-role.kubernetes.io/worker=worker;
          kubectl label nodes {{item}} workerselector=dls-worker-node --overwrite=true;
          kubectl label nodes {{item}} accelerator=huawei-Ascend910 --overwrite=true;
          kubectl label nodes {{item}} host-arch=huawei-arm --overwrite=true
      tags: init-workers
      with_inventory_hostnames:
        - training_node
      when: ansible_architecture == "aarch64"

    - name: Label training nodes - x86_64
      shell:
        cmd:
          kubectl label nodes {{item}} node-role.kubernetes.io/worker=worker;
          kubectl label nodes {{item}} workerselector=dls-worker-node --overwrite=true;
          kubectl label nodes {{item}} accelerator=huawei-Ascend910 --overwrite=true;
          kubectl label nodes {{item}} host-arch=huawei-x86 --overwrite=true
      tags: init-workers
      with_inventory_hostnames:
        - training_node
      when: ansible_architecture == "x86_64"

    - name: Label worker nodes - arm64
      shell:
        cmd:
          kubectl label nodes {{item}} node-role.kubernetes.io/worker=worker;
          kubectl label nodes {{item}} workerselector=dls-worker-node --overwrite=true;
          kubectl label nodes {{item}} accelerator=huawei-Ascend310 --overwrite=true;
          kubectl label nodes {{item}} host-arch=huawei-arm --overwrite=true
      tags: init-workers
      with_inventory_hostnames:
        - inference_node
      when: ansible_architecture == "aarch64"

    - name: Label worker nodes - x86_64
      shell:
        cmd:
          kubectl label nodes {{item}} node-role.kubernetes.io/worker=worker;
          kubectl label nodes {{item}} workerselector=dls-worker-node --overwrite=true;
          kubectl label nodes {{item}} accelerator=huawei-Ascend310 --overwrite=true;
          kubectl label nodes {{item}} host-arch=huawei-x86 --overwrite=true
      tags: init-workers
      with_inventory_hostnames:
        - inference_node
      when: ansible_architecture == "x86_64"
