---
# This playbook is used to modify system configurations on the master and worker nodes before all deployment.
# Make sure that this script is executed first.

- hosts: cluster
  remote_user: root

  tasks:
    - name: Close firewall
      shell:
        cmd:
          ufw disable

    # delete router forward config
    - name: Delete restrictive forwarding
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "net.ipv4.ip_forward(.*)=(.*)0"
        state: absent

    # add router forward config
    - name: Allow packet forwarding
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        state: present

    - name: Allow packet forwarding next
      lineinfile:
        path: /etc/rc.local
        line: "/usr/sbin/iptables -P FORWARD ACCEPT"
        create: yes

    - name: Network config
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
        create: yes

    # close swap and remove swap mount
    - name: Network config step && Close swap && Remove swap mount
      shell:
        cmd:
          modprobe br_netfilter;
          swapoff -a;
          sed -i 's/.*swap.*/#&/' /etc/fstab;

    # configure the Go environment
    - name: Add ENV
      blockinfile:
        path: /etc/profile
        block: |
          export GOROOT=/usr/local/go
          export GOPATH=/home/gopath
          export PATH=$PATH:/usr/local/go/bin
      tags: go

    - name: Add ENV for non-login shell
      blockinfile:
        path: ~/.bashrc
        block: |
          export GOROOT=/usr/local/go
          export GOPATH=/home/gopath
          export PATH=$PATH:/usr/local/go/bin
      tags: go

    - name: Enable config
      shell:
        cmd:
          source /etc/profile;
      args:
        executable: "/bin/bash"
      tags: go

    - name: Add User
      shell:
        cmd:
          useradd -d /home/hwMindX -u 9000 -m -s /bin/bash hwMindX || true;
          usermod -a -G HwHiAiUser hwMindX

- hosts: nfs_server
  remote_user: root

  tasks:
  - name: Add User
    shell:
      cmd:
        useradd -d /home/hwMindX -u 9000 -m -s /bin/bash hwMindX || true;
        useradd -d /home/HwHiAiUser -u 1000 -m -s /bin/bash HwHiAiUser || true;
        usermod -a -G HwHiAiUser hwMindX