apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ pvc_name }}
  namespace: {{ K8S_NAMESPACE }}
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: {{ capacity }}
  volumeName: storage-pv-mindx-dl
