---
# distribute resources
- hosts:
    - master
    - worker
    - harbor
    - master_backup
  roles:
    - role: mindx.resource
      vars:
        resource_list:
          - linux_aarch64
          - linux_x86_64
          - ubuntu_18.04_aarch64
          - ubuntu_18.04_x86_64
          - ubuntu_20.04_x86_64
          - centos_7_aarch64
          - openEuler_20.03_x86_64
          - kylin_V10_x86_64

# copy nfs resources to nfs_server host
- hosts:
    - nfs_server
  roles:
    - role: mindx.resource
      when: STORAGE_TYPE == "NFS"
      vars:
        resource_list:
          - ubuntu_18.04_aarch64
          - ubuntu_18.04_x86_64
          - ubuntu_20.04_x86_64
          - centos_7_aarch64
          - openEuler_20.03_x86_64
          - kylin_V10_x86_64

# copy harbor install package to harbor host
- hosts: harbor
  gather_facts: False
  roles:
    - role: mindx.resource
      vars:
        resource_list:
          - harbor-offline-installer-v2.3.3.tgz
          - harbor-offline-installer-aarch64-v2.3.3.tgz
