---
# install harbor
- hosts:
    - harbor
  roles:
    - role: mindx.docker
    - role: mindx.harbor.install

- hosts:
    - master
    - worker
    - master_backup
  roles:
    - role: mindx.harbor.login
