---
- hosts:
    - harbor
    - ceph_localhost
    - ceph_otherhost
  tasks:
  - name: set HARBOR_IP
    include_tasks: task_set_harbor_ip.yaml

# pull and rename images
- hosts:
    - ceph_localhost
    - ceph_otherhost
  gather_facts: False
  roles:
    - role: harbor.pull
