---
- hosts:
    - harbor
    - master
  tasks:
  - name: set HARBOR_IP
    include_tasks: task_set_harbor_ip.yaml

# master install redis
- hosts: master
  gather_facts: False
  roles:
    - role: mindx.redis
